[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = ["dotnet publish src/AspNetApiTemplate/AspNetApiTemplate.csproj -c Release -o out"]

[start]
cmd = "dotnet out/AspNetApiTemplate.dll"

